### ISSUE TITLE
TwaLauncher does not opens links on Meizu

### ISSUE THREAD

**Issue by TalbotGooday** [GoogleChrome/android-browser-helper#108]
I'm trying to open link like this:

`TwaLauncher(context).launch(Uri.parse(url))`

It works good on any devices, except the Meizu

I've tested on Meizu PRO 5. Android 5.1 (SDK: 22) 

Maybe I do something wrong. I don't even understand how to enable logging on TwaLauncher to improve the bug report.

I hope for your help. Thank you

**Comment by PEConn** [comment]
Hey,

If you try running the [twa-basic](https://github.com/GoogleChrome/android-browser-helper/tree/master/demos/twa-basic) demo, does that work?

TwaLauncher doesn't have optional logging - it's got some logging built in, but you can't really turn it on or off. To see the logs, you'll need to use `adb log` ([more info here](https://developer.android.com/studio/command-line/logcat)), but if you're using Android Studio, it should automatically show you the logs when you're trying to run.

Also, what browsers do you have installed on your phone, and which one is the default?

**Comment by TalbotGooday** [comment]
Unfortunately, all I have is information about the device and a complaint from the client that the links do not open. 
I wanted to use logging to send a report to my server. It is a pretty sad that the opportunity is missing. It seems that the only option is to capture logcat logs. Perhaps it makes sense to create a pull request with an optional logging :D 

It may be worth returning to this question when I have a physical device in my hands. Sorry. This issue was stupid :D

**Comment by PEConn** [comment]
Oh, so this is an issue that a user was experiencing? Did you get any crash report in the Play Console about it?

I vaguely remember seeing Flyme OS in a bug report for something else a few years ago and I think the upshot was that it uses some very zealous background task killer that killed Chrome before it had even launched.

As for logging, feel free to open a pull request although I'm not sure how much we want to dictate what logging framework users of this library would be using (and we're also somewhat sensitive to binary size). For a temporary workaround I'd suggest making a clone of this repo to build against and adding logging for yourself.

**Comment by TalbotGooday** [comment]
Thanks for the answer.

The funny thing is that there are no crashes, nothing just happens :D 
I also not really sure I want to add a "naked" source code or my own browser-helper build to my project, 'cause this is a chat SDK and probably some developer might want to exclude the browser-helper library to update or downgrade it for some reason.

But I really appreciate for your advice. If I find the reason for this behavior, I will definitely inform or create a pull request :+1:

**Comment by dalexanco** [comment]
Working in this issue too... I have noticed that this error happen many times when I launch my TWA app :
```
javax.net.ssl.SSLHandshakeException: Unacceptable certificate: CN=GTS CA 1C3, O=Google Trust Services LLC, C=US
```

I also have firebase that cant init itself :
```
E/FirebaseMessaging: Failed to get FIS auth token
    java.util.concurrent.ExecutionException: com.google.firebase.installations.FirebaseInstallationsException: Firebase Installations Service is unavailable. Please try again later.
        at com.google.android.gms.tasks.Tasks.zza(com.google.android.gms:play-services-tasks@@17.2.1:5)
        at com.google.android.gms.tasks.Tasks.await(com.google.android.gms:play-services-tasks@@17.2.1:8)
        at com.google.firebase.messaging.GmsRpc.setDefaultAttributesToBundle(com.google.firebase:firebase-messaging@@22.0.0:11)
        at com.google.firebase.messaging.GmsRpc.startRpc(com.google.firebase:firebase-messaging@@22.0.0:1)
        at com.google.firebase.messaging.GmsRpc.getToken(com.google.firebase:firebase-messaging@@22.0.0:2)
        at com.google.firebase.messaging.FirebaseMessaging.lambda$blockingGetToken$8$FirebaseMessaging(com.google.firebase:firebase-messaging@@22.0.0:1)
        at com.google.firebase.messaging.FirebaseMessaging$$Lambda$9.start(com.google.firebase:firebase-messaging@@22.0.0)
        at com.google.firebase.messaging.RequestDeduplicator.getOrStartGetTokenRequest(com.google.firebase:firebase-messaging@@22.0.0:6)
        at com.google.firebase.messaging.FirebaseMessaging.lambda$blockingGetToken$9$FirebaseMessaging(com.google.firebase:firebase-messaging@@22.0.0:1)
        at com.google.firebase.messaging.FirebaseMessaging$$Lambda$8.then(com.google.firebase:firebase-messaging@@22.0.0)
        at com.google.android.gms.tasks.zze.run(com.google.android.gms:play-services-tasks@@17.2.1:1)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)```
