### ISSUE TITLE
Hide address bar when custom tab fallback strategy is applied.

### ISSUE THREAD

**Issue by mohit1993** [GoogleChrome/android-browser-helper#238]
Hi,

1. I am unable to replicate when my TWA will fallback to custom tab, but i wonder when it happens whether there will be a address bar? if yes how can i hide that?
2. Another question is if my digital assests link fails as a cornor case whether TWA will be redirected to fallback strategy? or it just it will show address bar.

In general i don't want to show address bar in any case, kindly help here.

**Comment by mohit1993** [comment]
In addition to this i tried to run my TWA on Internet Explorer, i know TWA does not support IE, but i getting an error:
2020-12-10 16:00:05.138 12389-12389/com.microsoft.whiteboard E/PackageIdentity: Could not get fingerprint for package.
    android.content.pm.PackageManager$NameNotFoundException
        at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:266)
        at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:235)
        at com.microsoft.intune.mam.client.content.pm.PolicyPackageManager.getPackageInfo(PolicyPackageManager.java:362)
        at com.microsoft.intune.mam.client.content.pm.PackageManagementBehaviorImpl.getPackageInfo(PackageManagementBehaviorImpl.java:291)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.microsoft.intune.mam.InterProxy$InterInvocationHandler.invoke(InterProxy.java:86)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy9.getPackageInfo(Unknown Source)
        at com.microsoft.intune.mam.client.content.pm.MAMPackageManagement.getPackageInfo(MAMPackageManagement.java:228)
        at androidx.browser.trusted.PackageIdentityUtils$Api28Implementation.getFingerprintsForPackage(PackageIdentityUtils.java:85)
        at androidx.browser.trusted.PackageIdentityUtils.getFingerprintsForPackage(PackageIdentityUtils.java:47)
        at androidx.browser.trusted.Token.create(Token.java:63)
        at com.google.androidbrowserhelper.trusted.TwaLauncher.launch(TwaLauncher.java:192)
        
And nothing is happening on Ui , just a really bad experience can i intercept these exceptions. 
I guess this was the case when Fallback to webview or custom tabs should happen but received above error.

**Comment by andreban** [comment]
> Hi,
> 
> 1. I am unable to replicate when my TWA will fallback to custom tab, but i wonder when it happens whether there will be a address bar? if yes how can i hide that?
> 2. Another question is if my digital assests link fails as a cornor case whether TWA will be redirected to fallback strategy? or it just it will show address bar.
> 
> In general i don't want to show address bar in any case, kindly help here.

You can use the [WebView fallback ](https://github.com/GoogleChrome/android-browser-helper/blob/master/androidbrowserhelper/src/main/java/com/google/androidbrowserhelper/trusted/WebViewFallbackActivity.java) if you don't want the address bar to show in any case. Here's a [sample app](https://github.com/GoogleChrome/android-browser-helper/tree/master/demos/twa-webview-fallback) using it. It is, however, advisable to thoroughly test your application using the the WebView fallback, as it's not 100% compatible with all web APIs, and that's why the default is Custom Tabs.
