### ISSUE TITLE
PackageManger: NameNotFoundException raised while launching TWA

### ISSUE THREAD

**Issue by mohit1993** [GoogleChrome/android-browser-helper#258]
I am facing failure to launch TWA for my app, No fatal in app but TWA is not getting launched , look like error below is causing this:
2021-02-04 12:13:53.032 2169-2169/? W/System.err: android.content.pm.PackageManager$NameNotFoundException: com.microsoft.whiteboard.beta
2021-02-04 12:13:53.032 2169-2169/? W/System.err: at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:419)
2021-02-04 12:13:53.032 2169-2169/? W/System.err: at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:400)
2021-02-04 12:13:53.032 2169-2169/? W/System.err: at com.oneplus.util.OpUtils.updateTopPackage(OpUtils.java:429)
2021-02-04 12:13:53.032 2169-2169/? W/System.err: at com.android.systemui.statusbar.phone.NavigationBarFragment.notifyNavBarColorChanged(NavigationBarFragment.java:1500)
2021-02-04 12:13:53.032 2169-2169/? W/System.err: at com.android.systemui.statusbar.NavigationBarController.notifyNavBarColorChanged(NavigationBarController.java:295)
2021-02-04 12:13:53.032 2169-2169/? W/System.err: at com.android.systemui.statusbar.CommandQueue$H.handleMessage(CommandQueue.java:1315)
2021-02-04 12:13:53.032 2169-2169/? W/System.err: at android.os.Handler.dispatchMessage(Handler.java:107)
2021-02-04 12:13:53.032 2169-2169/? W/System.err: at android.os.Looper.loop(Looper.java:214)
2021-02-04 12:13:53.032 2169-2169/? W/System.err: at android.app.ActivityThread.main(ActivityThread.java:7710)
2021-02-04 12:13:53.032 2169-2169/? W/System.err: at java.lang.reflect.Method.invoke(Native Method)
2021-02-04 12:13:53.032 2169-2169/? W/System.err: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
2021-02-04 12:13:53.032 2169-2169/? W/System.err: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

This is happening many devices for user but not on my device, one user told me its happening on One Plus devices, Kindly help here.

**Comment by andreban** [comment]
Which version of android-browser-helper are you using in the app?

**Comment by mohit1993** [comment]
2.1.0

Though exception suggests it might be problem from Oneplus devices but any help here would be really appreciated

**Comment by andreban** [comment]
The exception seems to indicate that the app is trying to launch `com.microsoft.whiteboard.beta` (which I couldn't find on the Play Store to download and try to reproduce). Is your application using {`TwaProviderPicker`](https://github.com/GoogleChrome/android-browser-helper/blob/master/androidbrowserhelper/src/main/java/com/google/androidbrowserhelper/trusted/TwaProviderPicker.java) to find which browser to launch?

**Comment by gstepniewski-google** [comment]
Closing due to no updates in 5+ years
