### ISSUE TITLE
Loop crash when no browser 

### ISSUE THREAD

**Issue by dalexanco** [GoogleChrome/android-browser-helper#351]
**Describe the bug**
We discovered an issue when using the CCT fallback strategy. The application crashes in a loop when no browser available. 

**To Reproduce**
1. Open a TWA application on a device without any browser installed
4. See error : stuck on the splashscreen and then crash

**Expected behavior**
It should close the app gracefully and warn the user with a toast for example

**Did this ever used to work**
Don't think so

**Code Snippets**
```
E/PackageIdentity: Could not get fingerprint for package.
    android.content.pm.PackageManager$NameNotFoundException
        at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:286)
        at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:258)
        at androidx.browser.trusted.PackageIdentityUtils$Api28Implementation.getFingerprintsForPackage(PackageIdentityUtils.java:85)
        at androidx.browser.trusted.PackageIdentityUtils.getFingerprintsForPackage(PackageIdentityUtils.java:47)
        at androidx.browser.trusted.Token.create(Token.java:63)
        at com.google.androidbrowserhelper.trusted.TwaLauncher.launch(TwaLauncher.java:190)
```

**Smartphone (please complete the following information):**
 - Device: Galaxy S21 5G
 - OS: Android 12
 - Browsers Installed : None
 - android-browser-helper library version : 2.3.0

**Comment by PEConn** [comment]
Oh wow, that's impressive - how did you manage to get a device with no browser installed what-so-ever?

I think we had always assumed that there would be some browser on the device.

**Comment by dalexanco** [comment]
Simply disabled them using adb :) But yeah, it should not happen frequently
It's not an high priority bug I know, I just saw this behaviour and shared it :)

Close the issue if you want ;)

**Comment by gstepniewski-google** [comment]
Fixed by #575
